export default [
  {
    title: "Kandy",
    optionName: ["City Tour", "Day Tour"],
    options: [
      {
        id: 1,
        name: "Kandy Heritance",
        type: "city",
        itenary: [
          "Sri Dalada Maligawa (Temple of the Tooth Relic): Begin your tour with a visit to this iconic temple, learning about its history and significance in Buddhism.",
          "Kandy View Point",
          "Kandy Lake walk",
          "Kandy Gem Museum: Explore the gem museum to discover the various gemstones found in Sri Lanka, their history, and see artisans working on gem cuts.",
          "Cultural Show: End the day with a lively cultural show featuring traditional Sri Lankan dance and music performances to experience the local culture.",
        ],
        price: 49,
      },
      {
        id: 2,
        name: "Kandy Explorer",
        type: "city",
        itenary: [
          "Udathalawinna Viharaya: Start your tour at this serene Buddhist temple located a bit outside Kandy, known for its beautiful setting and peaceful atmosphere.",
          "Kandy Gem Museum: Visit the gem museum to learn about Sri Lanka’s gem trade and view exquisite gemstone displays.",
          "Royal Botanical Gardens: Conclude with a trip to the stunning royal botanical gardens in Peradeniya, known for its vast collection of plants and beautiful landscapes.",
          "Kandy View Point",
          "Kandy Lake: Enjoy a leisurely walk around Kandy Lake, taking in the views and the tranquility of the surroundings.",
          "Cultural Show: End the tour with a traditional cultural performance, experiencing the colorful history and culture of Sri Lanka.",
        ],
        price: 49,
      },
      {
        id: 3,
        name: "Kandy Highlights",
        type: "city",
        itenary: [
          "Kandy Market: Start by visiting the local market to experience the vibrant atmosphere, taste local snacks, and shop for handicrafts.",
          "Bahirawakanda Vihara Buddha Statue: After the museum, visit the impressive Buddha statue on a hilltop for panoramic views of the city.",
          "Kandy Gem Museum: Proceed to the gem museum to gain insights into Sri Lanka's rich gem heritage—perfect for gemstone enthusiasts.",
          "Kandy Lake walk",
          "Kandy View Point",
          "Cultural Show: End the tour with a traditional cultural performance, experiencing the colorful history and culture of Sri Lanka.",
        ],
        price: 49,
      },
      {
        id: 4,
        name: "Kandy Escape",
        type: "city",
        itenary: [
          "Ambuluwawa Tower",
          "Peradeniya Botanical Garden",
          "Kandy Gem Museum: Proceed to the gem museum to gain insights into Sri Lanka's rich gem heritage—perfect for gemstone enthusiasts.",
          "Bahirawakanda Vihara Buddha Statue: After the museum, visit the impressive Buddha statue on a hilltop for panoramic views of the city.",
          "Cultural Show: End the tour with a traditional cultural performance, experiencing the colorful history and culture of Sri Lanka.",
          "Temple of the Tooth Relic (Sri Dalada Maligawa): Visit this sacred Buddhist site, which houses a tooth relic of Buddha. You can explore the temple complex and learn about its historical significance.",
        ],
        price: 49,
      },
      {
        id: 5,
        name: "Kandy Rock Star",
        type: "day",
        itenary: [
          "Sigiriya Lion Rock",
          "Dambulla Cave Temple",
          "Matale Spice Garden",
          "Matale Hindu Temple",
          "Cultural Show",
          "Temple of Tooth",
        ],
        price: 89,
      },
      {
        id: 6,
        name: "Kandy Chill & Hill",
        type: "day",
        itenary: [
          "Ambuluwawa Tower",
          "Ramboda Waterfall",
          "Tea Plantation visit",
          "Hanuman Temple",
          "Cultural Show",
          "Temple of Tooth",
        ],
        price: 89,
      },
      {
        id: 7,
        name: "Kandy Animal Lovers",
        type: "day",
        itenary: [
          "Pinnawala Elephant Orphanage/Foundation",
          "Herbal Spice Garden",
          "Bird's Park Kandy",
          "Udawaththa Kele visit",
          "Cultural Show",
          "Temple of Tooth",
        ],
        price: 89,
      },
      {
        id: 8,
        name: "Kandy Wild Safari",
        type: "day",
        itenary: [
          "Wasgamuwa Safari or Minneriya Safari",
          "Spice Garden Visit",
          "Cultural Show",
          "Temple of Tooth",
        ],
        price: 89,
      },
      {
        id: 9,
        name: "Kandy Hike and Spike",
        type: "day",
        itenary: [
          "Ambuluwawa Tower",
          "Udawaththakele Forest",
          "Alagalla Mountain (Potato Hill)",
          "Knuckles Mountain Range",
          "Hanthana Mountain Range",
          "Cultural Show",
          "Temple of Tooth",
        ],
        price: 89,
      },
    ],
    customizedOptions: [
      "Temple of the Tooth Relic (Sri Dalada Maligawa): Visit this sacred Buddhist site, which houses a tooth relic of Buddha. You can explore the temple complex and learn about its historical significance.",
      "Kandy Lake: Enjoy a leisurely stroll around the picturesque Kandy Lake, located near the temple. You can also hire a boat for a serene experience on the water.",
      "Royal Botanical Gardens: Located in Peradeniya, just outside Kandy, these gardens are home to a vast collection of orchids and other plants. It's a great place for a relaxing walk and picnicking.",
      "Cultural Show: Attend a traditional Sri Lankan cultural show featuring dance performances and live music that showcase the island's rich cultural diversity.",
      "Kandy View Point: Hike or drive up to Kandy View Point for panoramic views of the city and the surrounding mountains, especially beautiful at sunset.",
      "Bahirawakanda Vihara Buddha Statue: Visit this massive seated Buddha statue on a hilltop that offers incredible views of Kandy.",
      "Spice Garden Tour: Take a tour of a local spice garden to learn about the various spices Sri Lanka is famous for, and perhaps even participate in a cooking class.",
      "Elephant Sanctuary: Visit the Pinnawala Elephant Orphanage (a bit outside Kandy) to see elephants being cared for. You can feed them and watch them bathe in the river.",
      "Kandy Market: Explore the local market for unique handicrafts, spices, and traditional Sri Lankan sweets. It’s a great place to experience local culture.",
      "Hiking and Nature Walks: Consider joining guided hikes in the nearby Knuckles Mountain Range for breathtaking views, diverse flora and fauna, and the chance to experience Sri Lanka’s natural beauty.",
      "Wasgamuwa National Park: A sprawling reserve about 80 km northeast of Kandy, home to wild elephants, sambar deer, water buffalo, and a variety of bird species; enjoy jeep safaris to spot wildlife in its natural habitat.",
      "Minneriya National Park: Famous for the annual “Gathering,” where hundreds of elephants congregate on the park’s lake shores between June and September, as well as dry-zone birdlife and other mammals.",
      "Wood Carving Workshops: Visit traditional carving villages (e.g., Embekke) to see master artisans shape ebony and satinwood into intricate masks, statues, and household items, and try your hand at carving basics.",
      "Birds’ Park Kandy: A compact aviary featuring over 100 species—both native and exotic—in landscaped enclosures; ideal for close-up views of hornbills, lorikeets, and kingfishers.",
      "Sigiriya Lion Rock: A UNESCO World Heritage Site northwest of Kandy—climb the dramatic “Lion’s Paw” rock fortress built in the 5th century CE for panoramic views, frescoes, and ancient water gardens.",
      "Dambulla Cave Temple: Also called the Golden Temple of Dambulla, this complex of five caves houses over 150 Buddha statues and vivid murals covering more than 2,000 m² of rock surface.",
      "Matale Hindu Temple (Sri Muthumariamman Kovil): A brightly painted Dravidian-style temple in Matale, renowned for its intricate gopuram (tower) and the annual Mariamman festival attracting thousands of devotees.",
      "Aluvihara Buddhist Temple, Matale: A secluded rock temple where ancient palm-leaf manuscripts of the Pāli Canon were preserved; explore meditation caves and centuries-old inscriptions.",
      "Nalanda Gedige: The island’s geographic and spiritual center, this 8th-century stone shrine blends Dravidian and Buddhist architecture—remarkably intact and set amid paddy fields.",
      "Dambulla Golden Temple (Exterior Shrine): The colossal gilded facade that greets visitors en route to the cave temples, featuring a 30-meter Buddha statue and a sweeping portico.",
      "Udathalawinna Temple: A peaceful hill-side monastery west of Kandy known for its meditation grounds, colorful murals, and an intact Buddha-footprint shrine.",
      "Ramboda Waterfall: A striking 109 m-high cascade on the A5 road between Kandy and Nuwara Eliya—stop at the viewing platform or nearby restaurants for tea with a view.",
      "Tea Factory Visit: Tour a working Ceylon tea factory to observe withering, rolling, oxidation, and drying; finish with a guided tasting of fresh brews.",
      "Kandy Esala Perahera Bookings: Secure seats for Sri Lanka’s most spectacular annual procession (usually mid-July to mid-August), featuring drummers, dancers, torchbearers, and the revered tooth relic casket.",
    ],
  },
  {
    title: "Colombo",
    intro:
      "Colombo, Sri Lanka's vibrant capital, blends modernity with tradition, offering visitors a dynamic mix of culture, history, and contemporary attractions. With its bustling streets, colorful markets, historic landmarks, and a lively beachfront, Colombo is a city that never sleeps. Whether you're discovering its colonial-era sites, enjoying local delicacies at street markets, or experiencing the vibrant nightlife, Colombo is an exciting destination that offers something for every traveler.",
    optionName: ["Day Tour"],
    options: [
      {
        id: 1,
        name: "Colombo",
        type: "day",
        itenary: [
          "Galle Face Green: Start your day with a stroll along this iconic oceanfront promenade, perfect for enjoying sea views, flying kites, or relaxing by the waves.",
          "Colombo National Museum: Dive into Sri Lanka’s rich history at this museum, home to fascinating exhibits on the island’s past and cultural heritage.",
          "Gangaramaya Temple: Visit this Buddhist temple, an architectural gem that blends traditional Sri Lankan design with elements from other cultures, offering a peaceful retreat in the heart of the city.",
          "Pettah Market: Experience the hustle and bustle of Colombo’s vibrant market district, where you can shop for local goods, spices, textiles, and souvenirs.",
          "Independence Square: Explore this historical site dedicated to Sri Lanka's independence, surrounded by beautiful parks and memorials.",
          "Colombo Harbour: Discover the port area, a vital hub of trade and activity for the island.",
          "Live Music & Bars (Evening): Head to lively bars and cafes offering local and international performances, where live bands and DJs play a mix of genres.",
          "Beachfront Dining (Evening): Enjoy dinner by the sea at the city’s coastal restaurants, offering fresh seafood, Sri Lankan specialties, and international cuisine.",
          "Nightlife Venues (Evening): From chic rooftop bars with stunning city views to nightclubs offering dancing and cocktails, Colombo has an array of options for night owls.",
          "Optional Night Walk: Explore the Colombo city lights on a nighttime walk, soaking in the city’s modern skyline and historical buildings illuminated after dark.",
        ],
        price: 89,
      },
    ],
  },
  {
    title: "Polonnaruwa",
    optionName: ["Day Tour"],
    options: [
      {
        id: 1,
        name: "Polonnaruwa",
        type: "day",
        itenary: [
          "Royal Palace Complex: Visit the ruins of the Royal Palace, where the Kings of Polonnaruwa once resided. The remains of the palace provide insight into the grandeur of the city during its peak.",
          "Gal Vihara: Admire the spectacular rock temple, where you’ll find four magnificent Buddha statues carved directly into the rock, including the iconic reclining Buddha.",
          "Parakrama Samudra: Take a serene walk around this vast ancient reservoir, built by King Parakramabahu I. The reservoir is a marvel of ancient engineering and a peaceful place to reflect.",
          "Watadage: Visit the circular stone structure that once housed sacred relics, surrounded by intricately carved stone pillars and a beautiful setting.",
          "Rankoth Vehera Stupa: One of the largest stupas in Polonnaruwa, Rankoth Vehera is a major pilgrimage site and a symbol of Sri Lanka’s Buddhist heritage.",
          "Lankatilaka Temple: Explore this impressive Buddhist temple, known for its giant standing Buddha statue and stunning frescoes, offering a glimpse into Polonnaruwa's religious significance.",
          "Siva Devale: Discover the Hindu temples that showcase the city’s diverse religious influences, with intricately carved statues of gods and kings.",
          "Cycling Tour: Rent a bike and cycle through the ancient ruins, enjoying the open-air museum-like setting of the city.",
          "Local Cuisine: Enjoy a traditional Sri Lankan meal at a local restaurant, with regional specialties that reflect the culinary heritage of the area.",
          "Optional - Sri Lanka's Ancient Rice Fields: Explore the surrounding rural areas to see traditional rice fields and farming methods that have remained unchanged for centuries.",
        ],
        price: 89,
      },
    ],
  },
  {
    title: "Sigiriya",
    optionName: ["Day Tour"],
    options: [
      {
        id: 1,
        name: "Sigiriya",
        type: "day",
        itenary: [
          "Sigiriya Rock Fortress: Climb to the top of this ancient rock citadel and explore the ruins of the royal palace, gardens, and frescoes. The panoramic views from the summit are nothing short of spectacular.",
          "Frescoes of Sigiriya: Admire the world-renowned frescoes of Sigiriya, which depict beautiful women believed to be celestial maidens.",
          "Lion's Gate: Walk through the remnants of the Lion’s Gate, an entrance to the royal palace that once featured a giant lion's head.",
          "Water Gardens: Explore the ancient water gardens that demonstrate the sophisticated irrigation system used by the ancient rulers.",
          "Pidurangala Rock (Optional): For those seeking a more adventurous hike, the Pidurangala Rock offers a different viewpoint of Sigiriya and is a great spot for photography.",
          "Cultural Dance Show (Optional): In the evening, enjoy a traditional Sri Lankan cultural dance performance, showcasing vibrant dances, drumming, and folklore.",
          "Sigiriya Village Tour (Optional): Take a short excursion to the nearby Sigiriya village for a local experience, including a traditional Sri Lankan meal or a peaceful bullock cart ride through the countryside.",
        ],
        price: 89,
      },
    ],
  },
  {
    title: "Galle",
    optionName: ["Day Tour"],
    options: [
      {
        id: 1,
        name: "Galle",
        type: "day",
        itenary: [
          "Galle Fort Exploration: Wander through the cobblestone streets of the 16th-century fortress, a UNESCO World Heritage site, and explore its historical buildings, museums, and ocean views.",
          "Unawatuna Beach: Relax at this popular beach with its calm waters, perfect for swimming and sunbathing.",
          "Dutch Reformed Church & Clock Tower: Visit these beautiful colonial-era landmarks that showcase Galle’s history.",
          "Sea Turtle Hatchery Visit: Learn about conservation efforts and interact with baby sea turtles at a local hatchery.",
          "Stilt Fishermen: Experience the unique and traditional method of fishing practiced along the coast.",
          "Galle Harbour: Take a walk around the bustling harbor, witnessing the blend of modern life and traditional fishing.",
          "Live Music & Bars (Evening): Enjoy performances by local bands in cozy bars and cafes, offering a relaxed yet vibrant atmosphere.",
          "Beachfront Dining (Evening): Dine at seaside restaurants offering fresh seafood and local specialties while enjoying the cool sea breeze.",
          "Night Markets (Evening): Explore the colorful night markets in Galle for souvenirs, snacks, and local crafts.",
          "Optional Night Safari: For those looking for a unique experience, embark on a night safari in nearby areas to spot wildlife.",
        ],
        price: 89,
      },
    ],
  },
  {
    title: "Jaffna",
    optionName: ["Day Tour"],
    options: [
      {
        id: 1,
        name: "Jaffna",
        type: "day",
        itenary: [
          "Jaffna Fort: Visit the 17th-century Dutch Fort, which stands as a testament to the region's colonial history and offers panoramic views of the city and surrounding coastline.",
          "Nallur Kandaswamy Kovil: One of the most revered Hindu temples in Sri Lanka, known for its stunning architecture and vibrant religious ceremonies.",
          "Jaffna Public Library: Explore one of Sri Lanka’s most famous libraries, which holds a deep significance for the Tamil community.",
          "Keerimalai Springs: Visit this sacred natural spring located by the sea, believed to have healing properties. The site is also home to the beautiful Naga Pooshani Ambal Kovil.",
          "Point Pedro: Visit the northernmost point of Sri Lanka, where the ocean meets the horizon. It's an excellent spot for photography and a peaceful retreat.",
          "Casuarina Beach: Relax at this quiet, scenic beach, perfect for swimming and unwinding.",
          "Local Markets: Visit the bustling Jaffna market for local produce, crafts, and traditional Tamil items.",
          "Sri Lankan Cuisine: Sample the region's delicious Jaffna-style cuisine, known for its spicy flavors, seafood, and unique dishes like Jaffna crab curry and dosai.",
          "Cultural Performances (Optional): Enjoy traditional Tamil dance or music performances, reflecting the rich artistic heritage of Jaffna.",
          "Island Tour (Optional): Take a short boat ride to Nainativu Island to visit the famous Nagadeepa Buddhist Temple or explore the ruins and wild horses of Delft Island.",
          "Ferry Ride to Jaffna Peninsula (Optional): Experience the scenic beauty of the Jaffna peninsula from the water with a short ferry ride.",
        ],
        price: 89,
      },
    ],
  },
  {
    title: "Ella",
    optionName: ["Day Tour"],
    options: [
      {
        id: 1,
        name: "Ella",
        type: "day",
        itenary: [
          "Ella Rock Hike: Enjoy panoramic views of valleys and tea plantations.",
          "Nine Arches Bridge: Capture the iconic railway bridge amidst lush greenery.",
          "Ravana Falls: Relax by this picturesque waterfall.",
          "Little Adam’s Peak: A short hike offering breathtaking views.",
          "Tea Plantation Visit: Learn about and taste Sri Lanka’s famous Ceylon tea.",
          "Flying Ravana Zipline (Optional): Optional thrilling zipline adventure.",
          "Live Music & Bands (Evening): Enjoy local and international music at various venues.",
          "Bars & Clubs (Evening): Relax or dance the night away with drinks and good vibes.",
          "Stargazing or Night Safari (Optional): Experience the serenity of the hills or explore wildlife after dark.",
        ],
        price: 89,
      },
    ],
  },
  {
    title: "Anuradhapura",
    optionName: ["Day Tour"],
    options: [
      {
        id: 1,
        name: "Anuradhapura",
        type: "day",
        itenary: [
          "Sri Maha Bodhi Tree: Visit one of the oldest living trees in the world, believed to be a sapling from the original tree under which Buddha attained enlightenment.",
          "Ruwanwelisaya Stupa: One of the tallest and most significant stupas in Sri Lanka, this magnificent monument stands as a testament to ancient Buddhist architecture and devotion.",
          "Jetavanarama Stupa: Admire the ruins of one of the largest brick structures in the world, once a center of Buddhist scholarship and pilgrimage.",
          "Abhayagiri Monastery: Explore this vast ancient monastic complex, which housed thousands of monks and was a major center of learning in the ancient world.",
          "Thuparamaya: Visit the first stupa built in Anuradhapura, said to house the relics of Buddha’s collarbone.",
          "Isurumuniya Temple: Famous for its beautiful rock carvings, this temple is a serene place to reflect on the city's deep religious history.",
          "Moonstone (Chandrasila): See the intricately carved moonstones that mark the entrances of many ancient buildings in Anuradhapura.",
          "Sacred City Walk: Take a reflective walk around the sacred city, where the spiritual aura and historical importance fill the air.",
          "Local Cuisine: Sample traditional Sri Lankan dishes at local eateries, offering a taste of Anuradhapura’s unique food culture.",
          "Optional - Mihintale Excursion: A short drive from Anuradhapura, Mihintale is known as the cradle of Buddhism in Sri Lanka, where King Devanampiyatissa converted to Buddhism after meeting the missionary Mahinda.",
          "Optional - Wilpattu National Park Safari: For nature and wildlife enthusiasts, an optional visit to nearby Wilpattu National Park offers an opportunity for a safari to see leopards, elephants, and a wide array of birdlife.",
        ],
        price: 89,
      },
    ],
  },
];
